# Generated by Django 5.0.6 on 2024-06-04 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('cena', models.FloatField()),
                ('slika', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Narudzbina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_narudzbine', models.DateTimeField(auto_now_add=True)),
                ('zavrsena', models.BooleanField(default=False)),
                ('broj_transakcije', models.CharField(max_length=100, null=True)),
                ('korisnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='InformacijeIsporuke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=200)),
                ('grad', models.CharField(max_length=200)),
                ('regija', models.CharField(max_length=200)),
                ('postanski_broj', models.CharField(max_length=200)),
                ('datum_dodavanja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.korisnik')),
                ('narudzbina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.narudzbina')),
            ],
        ),
        migrations.CreateModel(
            name='NarucenProizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('datum_dodavanja', models.DateTimeField(auto_now_add=True)),
                ('narudzbina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.narudzbina')),
                ('proizvod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.proizvod')),
            ],
        ),
    ]
